# Generated by Django 2.2.4 on 2019-08-10 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('provider', models.CharField(choices=[('AFRICAS_TALKING', 'Africas Talking'), ('TWILIO', 'Twilio')], default='AFRICAS_TALKING', max_length=30)),
                ('type', models.CharField(choices=[('NOTIFICATION', 'Notification'), ('REMINDER', 'Reminder'), ('ADVERTISEMENT', 'Advertisement')], default='NOTIFICATION', max_length=30)),
                ('sender', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMS',
                'ordering': ('-sent_at',),
            },
        ),
    ]
