# Generated by Django 2.2.4 on 2019-08-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190818_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostprofile',
            name='religion',
            field=models.CharField(blank=True, choices=[('CHI', 'Christian'), ('MUS', 'Muslim'), ('OTH', 'Other')], max_length=3, null=True),
        ),
    ]
