# Generated by Django 2.2.4 on 2019-08-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190825_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='hostprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
